#!/bin/bash

read -p "How old are you?" age

if [ $age -ge 16 ]
then
	echo "You can vote in Argentina!"
elif [ $age -eq 15 ]
then
	echo "You cannot vote in Argentina, but you can get a fake
	DNI and still manage your way through elections!"
else
	echo "You are not 15, and you are younger than 16"
fi

#Lee el proximo parametro y lo asigna a age
#Sintaxis de if
#Tener cuidado con los espacios, hacer esto:
#elif[ $age
#lanza error
